### ISSUE TITLE
Questions, Comments, and Concerns regarding CoCc Mandate TF Recommendations

### ISSUE THREAD

**Issue by kariljordan** [carpentries/task-forces#8]
On 2019-09-19, the Code of Conduct Committee Mandate Task Force released [recommendations](https://github.com/carpentries/task-forces/blob/master/2019/incidents-outside-cocc/2019-09-19-cocc-taskforce-summary-recommendations.md) for incidents that fall outside the CoCc's current mandate. We welcome questions, comments, and concerns about these recommendations. We'd like to keep track of feedback in one place (this GitHub issue) so that we can refer back to it should the task force decide to revise the language of the recommendations.

Please keep in mind [this report](https://github.com/carpentries/task-forces/blob/master/2019/incidents-outside-cocc/2019-09-19-cocc-taskforce-summary-recommendations.md) includes **recommendations**. A roadmap will be developed to determine how and when to approach implementing the recommendations. It will take a concerted effort from the entire community (staff, Executive Council, community members) to implement these recommendations.

**Comment by amyehodge** [comment]
I have a question about this. I’m trying to understand recommendations 2, 3 & 4 and exactly what the facilitators and ombudspersons are doing and when things are reported to where. Let me see if I understand this — and correct me if I’m wrong. Facilitators monitor our online spaces and possibly also live workshops and 1) can be approached by people about issues that concern people or 2) can identify issues themselves and then decide whether these are things that need to be reported to the CoCc. Whether they are reported to the CoCc or not, they should be reported to the Ombudsperson(s) (unclear why — to contact people for counseling?) and the Executive Committee. The Ombudsperson is more like a counselor and would also report appropriate items to the CoCc. Is this person/people also required to report all things to the EC, the point of which is so that the EC can include these in the transparency report and decide if any of these things falls within the purview of Recommendation 1?
I’m pretty sure I don’t have that entirely correct, but I’m having a little trouble drawing a flowchart for all this. Also, I feel like the ombudspersons job has been to report things to the CoCc, not be a counselor, so this seems like a shift there to me that is creating confusion for me, but perhaps I have misinterpreted that position up to now.
Thanks for any clarifications you can offer.

**Comment by kariljordan** [comment]
Thanks @amyehodge for this feedback. One of the distinctions we tried to make was between the idea of formal **'reporting'** and a more informal structure for **'sharing'** issues of concern. The recommendations around the Facilitators and the Ombudpersons are both to create a layer where people can **'share'** issues of concern without having to decide yet if they want to include the formal CoCc reporting structure as a part of the process. We found that this is currently a layer that's missing in our community, where people can share and discuss issues, and issues can be proactively identified. So, with regards to the Ombudpersons, we are recommending a potential shift and expansion of that role within our community, as a safe person that people can go to for whatever discussion is needed.

The way to move towards clarity is to map out how the implementation of these recommendations will look. As we move through the roadmap and implementation, we'll continue to ask for feedback, especially from people who have let us know they have specific concerns. That will help us clarify what the added layer of support will be.

**Comment by wrightaprilm** [comment]
I really appreciate the thought and effort on this, but it sounds like there's still a central issue of what happens when abuse is "off-campus." Recommendation One is really nicely stated. But what about the not-public response? This seems to mean that there is a set of activities
that the Carpentries will publicly respond to. But one of the cases the task force was convened about is someone feeling unsafe while doing their role in this community due to the presence of  their harasser. Full disclosure: this is me. I feel unsafe. I don't see how this report helps that situation.

I don't mean to be negative, because there is **so much** positive in this document, as I noted above!  We did a similar "Evo-Allies" program to the "CoC Facilitators" program, and it was awesome.  It's going to be great to see that here! But this also seems like the statement sidesteps  resolving a core issue that touches a lot of other issues in this community.

**Comment by kariljordan** [comment]
The following update is provided to bring this issue to a close.

Regarding **[Recommendation 2](https://github.com/carpentries/task-forces/blob/master/2019/incidents-outside-cocc/2019-09-19-cocc-taskforce-summary-recommendations.md#recommendation-2-volunteer-code-of-conduct-facilitators)**: The Code of Conduct Facilitators module is open for review and questions ([announcement](https://carpentries.org/blog/2021/06/code-of-conduct-facilitators-module/)). In summary, while maintaining the role of the Code of Conduct Committee (CoCc) as a Code of Conduct enforcement body, in the near future, Code of Conduct Facilitators will be trained and actively available to the community as a trusted and neutral point of counsel on Code of Conduct-related matters, monitor Carpentries online spaces and physical meetings and escalate Code of Conduct incidents for the attention of the CoCc or otherwise certify that the community is functioning as expected. The CoC Facilitators will share any incidents or concerns to an ombudsperson, directly with the Code of Conduct Committee and actively monitor of online Carpentries channels, and representatives in community calls, local, regional and global Carpentries events.

We invite community members to ask questions or initiate conversations around the module by [opening an issue on GitHub](https://github.com/carpentries/community-facilitators-program/issues/new). Your input will help us get the resource ready for Code of Conduct facilitator trainingsin the near future.
